CREATE ROLE slotera_app
  LOGIN
  PASSWORD 'slotera_app_local'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT;

GRANT CONNECT ON DATABASE slotera TO slotera_app;
GRANT USAGE ON SCHEMA public TO slotera_app;

ALTER DEFAULT PRIVILEGES FOR ROLE slotera_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO slotera_app;

ALTER DEFAULT PRIVILEGES FOR ROLE slotera_owner IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO slotera_app;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
